name: Exemplo de cron no GitHub Actions

on:
  schedule:
    - cron: "0 3 * * *"  # Executa diariamente às 3h (UTC)

jobs:
  mostrar-data:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir data e hora
        run: date
