name: Cypress Testes

on:
  schedule:
    - cron: '0 20,22,23 * * 1-5'

jobs:
  # O que será feito na pipeline
  cypress-run:
    # Maquina que será executado
    runs-on: ubuntu-24.04
    steps:
      # Passo a passo para rodar os testes
      - name: Checkout do Projeto
        uses: actions/checkout@v4

      # Instalando npm
      - name: Instalar dependências do projeto
        run: npm install

      # Iniciando os servidores ServerRest
        # - name: Iniciando os servidores MongoDB
        # run: npx serverest@latest

      # Roda os testes por fim
      - name: Rodando os testes do Cypress
        continue-on-error: true
        uses: cypress-io/github-action@v6
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: Evidências dos Testes
          path: cypress/reports/html/index.html
          # record: true
        # env: CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}