name: Cypress Testes Cron

on:
  schedule:
    - cron: '0 20,22,23 * * 2-5'

jobs:
  # O que será feito na pipeline
  cypress-run:
    # Maquina que será executado
    runs-on: ubuntu-24.04
    steps:
      # Passo a passo para rodar os testes
      - name: Checkout do Projeto
        uses: actions/checkout@v4

      # Instalando npm
      - name: Instalar dependências do projeto
        run: npm install --only=dev --loglevel=error

      # Iniciando os servidores ServerRest (Colocar aqui)

      # Roda os testes por fim
      - name: Rodando os testes do Cypress
        continue-on-error: true
        uses: cypress-io/github-action@v6
          with:
            record: true
          env: 
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: Evidências dos Testes
          path: cypress/reports/html/index.html